### ISSUE TITLE
Typesafe fields

### ISSUE THREAD

**Issue by sidoh** [LiveRamp/jack#75]
There should be a way to make an alternative to the `_Fields` enum which enables typesafe code. For example, we can have something like:

``` java
public static class _TypesafeFields extends JackFieldSet<Model> {
  public static final JackField<String> NAME = JackField.of(String.class);
  public static final JackField<Long> COUNT = JackField.of(Long.class);
}
```

which might be used in some kind of fancy type-safe query builder:

``` java
Set<Model> results = model.findBuilder()
    .where(Model._Fields.COUNT, 123L)
    .where(Model._Fields.NAME, "LiveRamp")
    .runQuery()
```

the `where` method might look something like:

``` java
public QueryBuilder where(JackField<T> field, T value) {
...
}
```

**Comment by tuliren** [comment]
This issue has been resolved by #141, which added typed columns and queries.
